import { defineStore } from "pinia";

export const useProductsStore = defineStore({
  id: "productsStore",
  state: () => ({
    products: {
      penneRigateNoodle: {
        sugarAmount: 17.5,
        productName: "Penne Rigate Pasta",
        amount: 500,
        model: "Nudeln_Penne.glb",
        meshMode: false,
        rotation: Math.PI / 2,
        amountPerPortion: 330,
        category: "noodles",
      },
      fusilliNoodle: {
        sugarAmount: 17.5,
        productName: "Fusilli Pasta",
        amount: 500,
        model: "Nudeln_Fusilli.glb",
        meshMode: false,
        rotation: Math.PI / 2,
        amountPerPortion: 330,
        category: "noodles",
      },
      spaghettiNoodle: {
        sugarAmount: 20,
        productName: "Spaghetti Pasta",
        amount: 500,
        model: "Nudeln_Spaghetti.glb",
        meshMode: false,
        rotation: Math.PI / 2,
        amountPerPortion: 330,
        category: "noodles",
      },
      finishedDishNoodle: {
        sugarAmount: 8.8,
        productName: "Finished Pasta Dish",
        amount: 367.2,
        scale: 0.28,
        model: "Nudeln_finishedDish.glb",
        meshMode: false,
        rotation: Math.PI / 2,
        amountPerPortion: 125.4,
        category: "fertig",
      },
      canCola: {
        sugarAmount: 35,
        productName: "Cola Cola",
        amount: 330,
        scale: 0.2,
        rotation: Math.PI / 4,
        model: "can_cola.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      canColaZero: {
        sugarAmount: 0,
        productName: "Coke Zero",
        amount: 330,
        scale: 0.2,
        rotation: Math.PI / 4,
        model: "can_colazero.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      canFanta: {
        sugarAmount: 34,
        productName: "Orange Soda",
        amount: 330,
        scale: 0.2,
        rotation: Math.PI / 4,
        model: "can_fanta.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      canSprite: {
        sugarAmount: 26,
        productName: "Citrus Soda",
        amount: 330,
        scale: 0.2,
        rotation: Math.PI / 4,
        model: "can_sprite.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      water: {
        sugarAmount: 0,
        productName: "Medium sparkling water",
        amount: 330,
        rotation: Math.PI / 4,
        scale: 0.3,
        model: "waterbottle.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      waterstill: {
        sugarAmount: 0,
        productName: "Non-Carbonated water",
        amount: 330,
        rotation: Math.PI / 4,
        scale: 0.3,
        model: "waterbottle_still.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      beer: {
        sugarAmount: 0,
        productName: "Beer",
        amount: 330,
        rotation: -Math.PI / 6,
        model: "beer.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      wine: {
        sugarAmount: 13,
        productName: "Wine",
        amount: 700,
        model: "wine.glb",
        rotation: -Math.PI / 4,
        scale: 0.4,
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      applejuice: {
        sugarAmount: 49,
        productName: "Apple Juice",
        amount: 500,
        model: "applejuice.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "drinks",
      },
      tomatoes: {
        sugarAmount: 12,
        productName: "Tomato 3-pack",
        amount: 240,
        scale: 0.18,
        model: "tomatoes.glb",
        meshMode: false,
        amountPerPortion: 0,
        category: "sauces",
      },
      stainedtomato: {
        sugarAmount: 24.5,
        productName: "Stained Tomatoes",
        amount: 500,
        scale: 0.15,
        model: "stainedTomato.glb",
        meshMode: false,
        amountPerPortion: 166,
        category: "sauces",
        rotation: Math.PI,
      },
      tomatosauce: {
        sugarAmount: 23.6,
        productName: "Tomato Sauce Basilico",
        scale: 0.2,
        rotation: Math.PI / 2,
        model: "sauce_basilico.glb",
        meshMode: false,
        amount: 400,
        amountPerPortion: 150,
        category: "sauces",
      },
      tomatosauceBolognese: {
        sugarAmount: 20,
        productName: "Tomato Sauce Bolognese",
        scale: 0.2,
        rotation: Math.PI / 2,
        model: "sauce_bolognese.glb",
        meshMode: false,
        amount: 400,
        amountPerPortion: 150,
        category: "sauces",
      },
      pesto: {
        sugarAmount: 17.6,
        productName: "Pesto Alla Genovese",
        scale: 0.2,
        rotation: Math.PI / 2,
        model: "sauce_pesto.glb",
        meshMode: false,
        amount: 400,
        amountPerPortion: 150,
        category: "sauces",
      },
      chips1: {
        sugarAmount: 3.6,
        productName: "Chips Sour Cream",
        scale: 0.35,
        meshMode: false,
        model: "chips1.glb",
        amount: 150,
        amountPerPortion: 50,
        category: "snacks",
      },
      chips2: {
        sugarAmount: 3.6,
        productName: "Chips Classic",
        scale: 0.35,
        meshMode: false,
        model: "chips2.glb",
        amount: 150,
        amountPerPortion: 50,
        category: "snacks",
      },
      chips3: {
        sugarAmount: 3.6,
        productName: "Chips Flamin' Hot",
        scale: 0.35,
        meshMode: false,
        model: "chips3.glb",
        amount: 150,
        amountPerPortion: 50,
        category: "snacks",
      },
      biscuitBox: {
        sugarAmount: 134,
        productName: "Wheat Biscuit Box",
        scale: 0.2,
        meshMode: false,
        model: "cookies_big.glb",
        amount: 800,
        amountPerPortion: 50,
        category: "snacks",
      },
      biscuitsSugarWheat: {
        sugarAmount: 67,
        productName: "Wheat Biscuits",
        scale: 0.3,
        meshMode: false,
        model: "cookies_small.glb",
        amount: 400,
        amountPerPortion: 50,
        category: "snacks",
      },
      biscuitsChocolate: {
        sugarAmount: 160,
        productName: "Chocolate Biscuits",
        scale: 0.3,
        meshMode: false,
        model: "cookies_small_choco.glb",
        amount: 400,
        amountPerPortion: 50,
        category: "snacks",
      },
      eggs: {
        sugarAmount: 0.5,
        productName: "Eggs",
        scale: 0.15,
        meshMode: false,
        model: "eggs.glb",
        amount: 400,
        amountPerPortion: 50,
        category: "sauces",
      },
    },
    shelves: [
      {
        name: "Noodles",
        boards: [
          {
            repeat: 2,
            products: [
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
            ],
          },
          {
            repeat: 2,
            products: [
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 1,
            products: [
              "water",
              "water",
              "water",
              "water",
              "water",
              "water",
              "water",
              "water",
              "water",
              "water",
            ],
          },
          {
            repeat: 1,
            products: [
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
              "waterstill",
            ],
          },
          {
            repeat: 2,
            products: [
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
            ],
          },
        ],
      },
      {
        name: "Noodles",
        boards: [
          {
            repeat: 4,
            products: [
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 1,
            products: [
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
              "canCola",
            ],
          },
          {
            repeat: 1,
            products: [
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
              "canFanta",
            ],
          },
          {
            repeat: 1,
            products: [
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
              "canSprite",
            ],
          },
          {
            repeat: 1,
            products: [
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
              "canColaZero",
            ],
          },
        ],
      },
      {
        name: "Noodles",
        boards: [
          {
            repeat: 4,
            products: [
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 2,
            products: [
              "wine",
              "wine",
              "wine",
              "wine",
              "wine",
              "wine",
              "wine",
              "wine",
            ],
          },
          {
            repeat: 2,
            products: [
              "beer",
              "beer",
              "beer",
              "beer",
              "beer",
              "beer",
              "beer",
              "beer",
            ],
          },
        ],
      },
      {
        name: "Sauces",
        boards: [
          {
            repeat: 1,
            products: [
              "eggs",
              "eggs",
              "eggs",
              "eggs",
              "eggs",
              "eggs",
              "eggs",
              "eggs",
              "eggs",
            ],
          },
          {
            repeat: 1,
            products: [
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
            ],
          },

          {
            repeat: 1,
            products: [
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
              "pesto",
            ],
          },
          {
            repeat: 1,
            products: [
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
            ],
          },
        ],
      },

      {
        name: "Snack",
        boards: [
          {
            repeat: 2,
            products: [
              "chips1",
              "chips1",
              "chips1",
              "chips1",
              "chips1",
              "chips1",
              "chips1",
            ],
          },
          {
            repeat: 1,
            products: [
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
              "chips2",
            ],
          },
          {
            repeat: 1,
            products: [
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
              "chips3",
            ],
          },
        ],
      },
      {
        name: "Tomatoes",
        boards: [
          {
            repeat: 2,
            products: [
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
            ],
          },
          {
            repeat: 2,
            products: [
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
            ],
          },
        ],
      },

      {
        name: "Snack",
        boards: [
          {
            repeat: 2,
            products: [
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
            ],
          },
          {
            repeat: 1,
            products: [
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
            ],
          },
          {
            repeat: 1,
            products: [
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
            ],
          },
        ],
      },
    ],
    testShelves: [
      {
        name: "Noodles",
        boards: [
          {
            repeat: 2,
            products: [
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 2,
            products: [
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
              "applejuice",
            ],
          },
        ],
      },
      {
        name: "Sauces",
        boards: [
          {
            repeat: 1,
            products: [
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
            ],
          },
        ],
      },

      {
        name: "Snack",
        boards: [
          {
            repeat: 2,
            products: [
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
            ],
          },
        ],
      },
    ],
  }),
  getters: {
    getItemsByCategory: (state) => (category: string) => {
      return state.products.filter((item) => item.category === category);
    },
    getAllItems: (state) => () => {
      return state.products;
    },
  },
  actions: {},
});
